name: (Develop) Deploy Web to AWS ECS
on:
  push:
    branches:
      - master
    paths:
      - container/sampleweb/**
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  ECR_REPOSITORY: arf-web
  ECS_CLUSTER: arf-cluster
  ECS_SERVICE: arf-web-service
  ECS_TASK_DEFINITION: arf-web-task
  IMAGE_TAG: latest
  CONTAINER_NAME: arf-web-container

jobs:
  deployment:
    name: Deploy Web to AWS ECS
    runs-on: ubuntu-latest
    environment: develop
    defaults:
      run:
        working-directory: ./container/sampleweb
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image to Amazon ECR
        id: build-image
        uses: docker/build-push-action@v5
        with:
          push: true
          context: ./container/sampleweb
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}
            ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
          platforms: linux/amd64

      - name: Download task definition
        run: |
          aws ecs describe-task-definition \
          --task-definition $ECS_TASK_DEFINITION \
          --query taskDefinition \
          --region ${{ vars.AWS_REGION }} > ../../task-definition.json
        
      - name: Remove enableFaultInjection key from task definition
        run: |
          jq \'del(.enableFaultInjection)\' ../../task-definition.json > ../../task-definition-temp.json && mv ../../task-definition-temp.json ../../task-definition.json

      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: ${{ env.CONTAINER_NAME }}
          image: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}
  
      - name: Deploy to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          wait-for-service-stability: true